language: python
python:
  - "3.6"
before_install:
  - pip install pygraphblas
  - pip install --upgrade "setuptools>=40.0"
install:
  - pip install -r requirements.txt
script:
  - python tests/test.py
